language: java

jdk:
  - oraclejdk7 

script: gradle check

before_script:
  - pip install --user codecov

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3fcba0ce3f352e5f7ebe
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
